spring:
  application:
    name: mall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.8:8848
  thymeleaf:
    cache: false
  redis:
    port: 6379
    host: 192.168.1.8
  session:
    store-type: redis

server:
  port: 20000
